<?php
$pageTitle='Staff Monthly Report'; require __DIR__.'/staff_common.php';
$month=$_GET['month']??date('Y-m'); $staffId=(int)($_GET['staff_id']??0); $staff=$pdo->query('SELECT * FROM staff WHERE active=1 ORDER BY name')->fetchAll(PDO::FETCH_ASSOC);
if(!$staffId && $staff) $staffId=(int)$staff[0]['id']; $r=$staffId?staffMonthReport($pdo,$staffId,$month):null;
include __DIR__.'/includes/header.php';
?>
<div class="card"><h1>Monthly Staff Report</h1><form method="get" class="form-grid"><select name="staff_id"><?php foreach($staff as $s):?><option value="<?=$s['id']?>" <?=$staffId==$s['id']?'selected':''?>><?=h($s['employee_code'].' - '.$s['name'])?></option><?php endforeach;?></select><input type="month" name="month" value="<?=h($month)?>"><button class="btn btn-accent">View</button><?php if($r):?><a class="btn" href="staff_monthly_report_pdf.php?staff_id=<?=$staffId?>&month=<?=h($month)?>">PDF</a><?php endif;?></form></div>
<?php if($r):?><div class="grid grid-4"><?php foreach(['Present','Absent','Off Day','Leave','Holiday'] as $k):?><div class="card"><div class="muted"><?=h($k)?></div><div class="metric"><?=$r['counts'][$k]?></div></div><?php endforeach;?></div><div class="grid grid-3"><div class="card"><div class="muted">Working Days</div><div class="metric"><?=$r['working']?></div></div><div class="card"><div class="muted">Paid Days</div><div class="metric"><?=$r['paidDays']?></div></div><div class="card"><div class="muted">Salary Payable</div><div class="metric"><?=moneyLkr($r['salary'])?></div></div></div><div class="card"><h2><?=h($r['staff']['name'])?> — <?=h(date('F Y',strtotime($month.'-01')))?></h2><table><tr><th>Date</th><th>Day</th><th>Status</th><th>Note</th></tr><?php foreach($r['rows'] as $row):?><tr><td><?=h($row['date'])?></td><td><?=h($row['day'])?></td><td><strong><?=h($row['status'])?></strong></td><td><?=h($row['label'])?></td></tr><?php endforeach;?></table></div><?php endif;?>
<?php include __DIR__.'/includes/footer.php'; ?>
