<?php
$pageTitle='Staff & Attendance'; require __DIR__.'/staff_common.php';
if(isset($_POST['action'])){
  try{
    if($_POST['action']==='save_staff'){
      $id=(int)($_POST['id']??0); $data=[trim($_POST['employee_code']),trim($_POST['name']),trim($_POST['phone']),trim($_POST['position']),$_POST['join_date']?:null,(float)$_POST['basic_salary'],(float)$_POST['allowance'],(float)$_POST['deduction'],(int)$_POST['weekly_off_day']];
      if($id){$st=$pdo->prepare('UPDATE staff SET employee_code=?,name=?,phone=?,position=?,join_date=?,basic_salary=?,allowance=?,deduction=?,weekly_off_day=? WHERE id=?');$st->execute([...$data,$id]);}
      else{$st=$pdo->prepare('INSERT INTO staff(employee_code,name,phone,position,join_date,basic_salary,allowance,deduction,weekly_off_day) VALUES(?,?,?,?,?,?,?,?,?)');$st->execute($data);}
    } elseif($_POST['action']==='delete_staff'){ $pdo->prepare('DELETE FROM staff WHERE id=?')->execute([(int)$_POST['id']]); }
    elseif($_POST['action']==='save_attendance'){ $st=$pdo->prepare("INSERT INTO staff_attendance(staff_id,attendance_date,status,notes) VALUES(?,?,?,?) ON CONFLICT(staff_id,attendance_date) DO UPDATE SET status=excluded.status, notes=excluded.notes"); if(defined('DB_DRIVER')&&DB_DRIVER==='mysql') $st=$pdo->prepare("INSERT INTO staff_attendance(staff_id,attendance_date,status,notes) VALUES(?,?,?,?) ON DUPLICATE KEY UPDATE status=VALUES(status), notes=VALUES(notes)"); $st->execute([(int)$_POST['staff_id'],$_POST['date'],$_POST['status'],trim($_POST['notes'])]); }
    elseif($_POST['action']==='save_holiday'){ $st=$pdo->prepare("INSERT INTO staff_holidays(holiday_date,holiday_name,paid) VALUES(?,?,?) ON CONFLICT(holiday_date) DO UPDATE SET holiday_name=excluded.holiday_name,paid=excluded.paid"); if(defined('DB_DRIVER')&&DB_DRIVER==='mysql') $st=$pdo->prepare("INSERT INTO staff_holidays(holiday_date,holiday_name,paid) VALUES(?,?,?) ON DUPLICATE KEY UPDATE holiday_name=VALUES(holiday_name),paid=VALUES(paid)"); $st->execute([$_POST['holiday_date'],trim($_POST['holiday_name']),isset($_POST['paid'])?1:0]); }
    elseif($_POST['action']==='save_leave'){ $st=$pdo->prepare("INSERT INTO staff_leave(staff_id,leave_date,leave_type,paid,notes) VALUES(?,?,?,?,?) ON CONFLICT(staff_id,leave_date) DO UPDATE SET leave_type=excluded.leave_type,paid=excluded.paid,notes=excluded.notes"); if(defined('DB_DRIVER')&&DB_DRIVER==='mysql') $st=$pdo->prepare("INSERT INTO staff_leave(staff_id,leave_date,leave_type,paid,notes) VALUES(?,?,?,?,?) ON DUPLICATE KEY UPDATE leave_type=VALUES(leave_type),paid=VALUES(paid),notes=VALUES(notes)"); $st->execute([(int)$_POST['staff_id'],$_POST['leave_date'],trim($_POST['leave_type']),isset($_POST['paid'])?1:0,trim($_POST['notes'])]); }
    header('Location: staff.php?ok=1'); exit;
  }catch(Throwable $e){$error=$e->getMessage();}
}
$staff=$pdo->query('SELECT * FROM staff WHERE active=1 ORDER BY name')->fetchAll(PDO::FETCH_ASSOC); $month=$_GET['month']??date('Y-m');
include __DIR__.'/includes/header.php';
?>
<div class="card"><h1>Staff & Attendance</h1><p>Manage employees, daily attendance, leave, holidays and monthly salary.</p><?php if(isset($error)):?><div class="alert alert-danger"><?=h($error)?></div><?php endif;?></div>
<div class="grid grid-2">
<div class="card"><h2>Add / Edit Staff</h2><form method="post"><input type="hidden" name="action" value="save_staff"><input type="hidden" name="id" value="0"><div class="form-grid"><input name="employee_code" placeholder="Employee Code" required><input name="name" placeholder="Full Name" required><input name="phone" placeholder="Phone"><input name="position" placeholder="Position"><input type="date" name="join_date"><input type="number" step="0.01" name="basic_salary" placeholder="Basic Salary" required><input type="number" step="0.01" name="allowance" placeholder="Monthly Allowance" value="0"><input type="number" step="0.01" name="deduction" placeholder="Monthly Deduction" value="0"><select name="weekly_off_day"><option value="0">Sunday</option><option value="1">Monday</option><option value="2">Tuesday</option><option value="3">Wednesday</option><option value="4">Thursday</option><option value="5">Friday</option><option value="6">Saturday</option></select></div><button class="btn btn-accent">Save Staff</button></form></div>
<div class="card"><h2>Daily Attendance</h2><form method="post"><input type="hidden" name="action" value="save_attendance"><div class="form-grid"><select name="staff_id" required><option value="">Select staff</option><?php foreach($staff as $s):?><option value="<?=$s['id']?>"><?=h($s['employee_code'].' - '.$s['name'])?></option><?php endforeach;?></select><input type="date" name="date" value="<?=date('Y-m-d')?>"><select name="status"><option>Present</option><option>Absent</option><option>Off Day</option><option>Leave</option><option>Holiday</option></select><input name="notes" placeholder="Notes"></div><button class="btn btn-accent">Save Attendance</button></form><hr><h3>Leave</h3><form method="post"><input type="hidden" name="action" value="save_leave"><div class="form-grid"><select name="staff_id" required><?php foreach($staff as $s):?><option value="<?=$s['id']?>"><?=h($s['name'])?></option><?php endforeach;?></select><input type="date" name="leave_date"><input name="leave_type" value="Annual Leave"><label><input type="checkbox" name="paid" checked> Paid Leave</label><input name="notes" placeholder="Notes"></div><button class="btn">Save Leave</button></form></div>
</div>
<div class="card"><h2>Public / Hotel Holidays</h2><form method="post" style="display:flex;gap:10px;flex-wrap:wrap"><input type="hidden" name="action" value="save_holiday"><input type="date" name="holiday_date" required><input name="holiday_name" placeholder="Holiday name" required><label><input type="checkbox" name="paid" checked> Paid</label><button class="btn">Save Holiday</button></form></div>
<div class="card"><h2>Staff List</h2><table><tr><th>Code</th><th>Name</th><th>Position</th><th>Basic</th><th>Report</th><th>Action</th></tr><?php foreach($staff as $s):?><tr><td><?=h($s['employee_code'])?></td><td><?=h($s['name'])?></td><td><?=h($s['position'])?></td><td><?=moneyLkr((float)$s['basic_salary'])?></td><td><a class="btn btn-sm" href="staff_monthly_report.php?month=<?=h($month)?>&staff_id=<?=$s['id']?>">Monthly Report</a> <a class="btn btn-sm btn-accent" href="staff_monthly_report_pdf.php?month=<?=h($month)?>&staff_id=<?=$s['id']?>">PDF</a></td><td><form method="post" onsubmit="return confirm('Delete staff?')"><input type="hidden" name="action" value="delete_staff"><input type="hidden" name="id" value="<?=$s['id']?>"><button class="btn btn-sm">Delete</button></form></td></tr><?php endforeach;?></table></div>
<?php include __DIR__.'/includes/footer.php'; ?>
